/*
 * Gizoffer
 *
 * Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package app

import (
	"github.com/gin-gonic/gin"
)

type UsersAPI interface {


    // UsersGet Get /users
    // Get all users 
     UsersGet(c *gin.Context)

    // UsersIdDelete Delete /users/:id
    // Delete a user by ID 
     UsersIdDelete(c *gin.Context)

    // UsersIdGet Get /users/:id
    // Get a user by ID 
     UsersIdGet(c *gin.Context)

    // UsersIdPut Put /users/:id
    // Update a user by ID 
     UsersIdPut(c *gin.Context)

    // UsersPost Post /users
    // Create a user 
     UsersPost(c *gin.Context)

}