/*
 * Gizoffer
 *
 * Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package app

import (
	"github.com/gin-gonic/gin"
)

type EntriesAPI interface {


    // EntriesIdDelete Delete /entries/:id
    // Delete an entry by ID 
     EntriesIdDelete(c *gin.Context)

    // EntriesIdGet Get /entries/:id
    // Get an entry by ID 
     EntriesIdGet(c *gin.Context)

    // EntriesPost Post /entries
    // Create an entry 
     EntriesPost(c *gin.Context)

}