/*
 * Gizoffer
 *
 * Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package app

import (
	"github.com/gin-gonic/gin"
)

type OffersAPI interface {

	// OffersGet Get /offers
	// Get all offers
	OffersGet(c *gin.Context)

	// OffersPost Post /offers
	// Create an offer
	OffersPost(c *gin.Context)

	// OffersUuidDelete Delete /offers/:uuid
	// Delete an offer by UUID
	OffersUuidDelete(c *gin.Context)

	// OffersUuidEntryDelete Delete /offers/:uuid/entry
	// Cancel an entry by UUID
	OffersUuidEntryDelete(c *gin.Context)

	// OffersUuidEntryPost Post /offers/:uuid/entry
	// Entry an offer by UUID
	OffersUuidEntryPost(c *gin.Context)

	// OffersUuidGet Get /offers/:uuid
	// Get an offer by UUID
	OffersUuidGet(c *gin.Context)

	// OffersUuidPut Put /offers/:uuid
	// Update an offer by UUID
	OffersUuidPut(c *gin.Context)
}
