/*
 * Gizoffer
 *
 * Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package app

import (
	"github.com/gin-gonic/gin"
)

type OffersAPI interface {


    // OffersGet Get /offers
    // Get all offers 
     OffersGet(c *gin.Context)

    // OffersIdDelete Delete /offers/:id
    // Delete an offer by ID 
     OffersIdDelete(c *gin.Context)

    // OffersIdGet Get /offers/:id
    // Get an offer by ID 
     OffersIdGet(c *gin.Context)

    // OffersIdPut Put /offers/:id
    // Update an offer by ID 
     OffersIdPut(c *gin.Context)

    // OffersPost Post /offers
    // Create an offer 
     OffersPost(c *gin.Context)

}