/*
 * Gizoffer
 *
 * Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package app

import (
	"github.com/gin-gonic/gin"
)

type UsersAPI interface {

	// LoginPost Post /login
	// Login
	LoginPost(c *gin.Context)

	// UsersPost Post /users
	// Create a user
	UsersPost(c *gin.Context)

	// UsersUuidGet Get /users/:uuid
	// Get a user by UUID
	UsersUuidGet(c *gin.Context)
}
