/*
 * Gizoffer
 *
 * Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package app

type UserPostRequest struct {

	Name string `json:"name"`

	Email string `json:"email"`

	Password string `json:"password"`
}
