/*
 * Gizoffer
 *
 * Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package app

type Entry struct {

	Id int32 `json:"id,omitempty"`

	UserId int32 `json:"user_id"`

	OfferId int32 `json:"offer_id"`
}
