/*
 * Gizoffer
 *
 * Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package app

import (
	"time"
)

type OfferGetResponse struct {

	Uuid string `json:"uuid"`

	Title string `json:"title"`

	Description string `json:"description"`

	ChatUrl string `json:"chat_url,omitempty"`

	Giz int32 `json:"giz,omitempty"`

	IsPublic bool `json:"is_public"`

	Deadline time.Time `json:"deadline"`

	EntryUsers []UserGetResponse `json:"entry_users,omitempty"`
}
