/*
 * Gizoffer
 *
 * Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package app

import (
	"time"
)

type Offer struct {

	Id int32 `json:"id,omitempty"`

	Title string `json:"title"`

	Description string `json:"description"`

	IsPublic bool `json:"is_public"`

	Deadline time.Time `json:"deadline"`
}
