/*
 * Gizoffer
 *
 * Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	sw "github.com/iotassss/gizoffer/internal/app"
	"github.com/iotassss/gizoffer/internal/database"
)

func main() {
	db := database.Connect()

	userHandler := sw.NewUserHandler(db)
	authApi := sw.NewAuthHandler(db)
	entryApi := sw.NewEntryHandler(db)
	offerApi := sw.NewOfferHandler(db)

	routes := sw.ApiHandleFunctions{
		UsersAPI:   userHandler,
		AuthAPI:    authApi,
		EntriesAPI: entryApi,
		OffersAPI:  offerApi,
	}

	log.Printf("Server started")

	router := sw.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
