openapi: 3.0.3
info:
  title: Gizoffer
  description: Gizoffer is a platform that helps you find the best deals with Gizomo employees using GIZ.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server
security:
  - BearerAuth: []
tags:
  - name: users
  - name: offers
  # - name: tags
  - name: entries
  - name: auth
paths:
  /login:
    post:
      summary: Login
      tags:
        - auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: yourpassword
      responses:
        '200':
          description: login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                  message:
                    type: string
                    example: "Login successful."
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid credentials."
  /users:
    get:
      summary: Get all users
      tags:
        - users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a user
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      summary: Get a user by ID
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: A user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Update a user by ID
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Delete a user by ID
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No content
  /offers:
    get:
      summary: Get all offers
      tags:
        - offers
      responses:
        '200':
          description: A list of offers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
    post:
      summary: Create an offer
      tags:
        - offers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Offer'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
  /offers/{id}:
    get:
      summary: Get an offer by ID
      tags:
        - offers
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: An offer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
    put:
      summary: Update an offer by ID
      tags:
        - offers
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Offer'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
    delete:
      summary: Delete an offer by ID
      tags:
        - offers
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No content
  /entries/{id}:
    get:
      summary: Get an entry by ID
      tags:
        - entries
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: An entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entry'
    put:
      summary: Update an entry by ID
      tags:
        - entries
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entry'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entry'
    delete:
      summary: Delete an entry by ID
      tags:
        - entries
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No content
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: uuid
          readOnly: true
        name:
          type: string
        email:
          type: string
          format: email
          writeOnly: true
        password:
          type: string
          format: password
          writeOnly: true
      required:
        - name
        - email
        - password
    Offer:
      type: object
      properties:
        id:
          type: integer
          format: uuid
          readOnly: true
        title:
          type: string
        description:
          type: string
        is_public:
          type: boolean
        deadline:
          type: string
          format: date-time
      required:
        - title
        - description
        - is_public
        - deadline
    Entry:
      type: object
      properties:
        id:
          type: integer
          format: uuid
          readOnly: true
        user_id:
          type: integer
          format: uuid
        offer_id:
          type: integer
          format: uuid
      required:
        - user_id
        - offer_id
  parameters:
    id:
      name: id
      in: path
      required: true
      description: ID of the resource
      schema:
        type: integer
        format: uuid
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
